version: "3.8"
services:
  email:
    build: .
    env_file: .env-email
    depends_on: 
      - db
   
    
  db:
    image: postgres
    restart: always
    env_file: .env-database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  